apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvlt-api
  namespace: rvlt-api
  labels:
    app: rvlt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvlt-api
  template:
    metadata:
      labels:
        app: rvlt-api
    spec:
      containers:
      - name: rvlt-api
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rvlt-api
  namespace: rvlt-api
spec:
  type: NodePort
  selector:
    app: rvlt-api
  ports:
    - name: rvlt-api
      port: 80
      targetPort: 8080

