name: CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: "poc-dev"         # set this to your Amazon ECR repository name
  
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: build
    runs-on: ubuntu-latest
    environment: development
   

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::472132854555:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
